lb:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
redis:
  image: redis
h2:
  image: making/h2-server
shop1:
  build: .
  # image: making/jsug-shop
  links:
    - redis
    - h2
  environment:
    VIRTUAL_HOST: jsug-shop.example.com
  command: >
    --spring.thymeleaf.cache=true
    --logging.level.jdbc.resultsettable=ERROR
    --logging.level.jdbc.sqltiming=ERROR
    --logging.level.org=WARN
    --spring.datasource.url=jdbc:h2:tcp://${H2_PORT_1521_TCP_ADDR}:${H2_PORT_1521_TCP_PORT}/~/jsug-shop
    --info.instance.name=shop1
shop2:
  build: .
  # image: making/jsug-shop
  links:
    - redis
    - h2
  environment:
    VIRTUAL_HOST: jsug-shop.example.com
  command: >
    --spring.thymeleaf.cache=true
    --logging.level.jdbc.resultsettable=ERROR
    --logging.level.jdbc.sqltiming=ERROR
    --logging.level.org=WARN
    --spring.datasource.url=jdbc:h2:tcp://${H2_PORT_1521_TCP_ADDR}:${H2_PORT_1521_TCP_PORT}/~/jsug-shop
    --info.instance.name=shop2
shop3:
  build: .
  # image: making/jsug-shop
  links:
    - redis
    - h2
  environment:
    VIRTUAL_HOST: jsug-shop.example.com
  command: >
    --spring.thymeleaf.cache=true
    --logging.level.jdbc.resultsettable=ERROR
    --logging.level.jdbc.sqltiming=ERROR
    --logging.level.org=WARN
    --spring.datasource.url=jdbc:h2:tcp://${H2_PORT_1521_TCP_ADDR}:${H2_PORT_1521_TCP_PORT}/~/jsug-shop
    --info.instance.name=shop3
